/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;

import java.awt.Desktop;
import java.io.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author carlop3333
 */
public class DatapackCreatorUI extends javax.swing.JFrame {

    /**
     * Creates new form DatapackCreatorUI
     */
    public DatapackCreatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoeditar1 = new javax.swing.JTextArea();
        guardar = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        MainBar = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenu();
        copy = new javax.swing.JMenuItem();
        paste = new javax.swing.JMenuItem();
        cut = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        delete_all = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ayuda = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        acercade = new javax.swing.JMenuItem();
        githubr = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bienvenido.setFont(new java.awt.Font("Hannotate SC", 0, 13)); // NOI18N
        bienvenido.setText("A datapack creator ");

        textoeditar1.setColumns(20);
        textoeditar1.setRows(5);
        jScrollPane1.setViewportView(textoeditar1);

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/save2x.png"))); // NOI18N
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        boton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/backspace1x.png"))); // NOI18N
        boton1.setText("Delete text");
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton1MouseClicked(evt);
            }
        });
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        archivo.setText("File");

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/new1x.png"))); // NOI18N
        nuevo.setText("New");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        archivo.add(nuevo);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/save1x.png"))); // NOI18N
        jMenuItem1.setText("Save ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        archivo.add(jMenuItem1);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/exit1x.png"))); // NOI18N
        salir.setText("Exit");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        archivo.add(salir);

        MainBar.add(archivo);

        editar.setText("Edit");

        copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/copy1x.png"))); // NOI18N
        copy.setText("Copy");
        copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyActionPerformed(evt);
            }
        });
        editar.add(copy);

        paste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/paste1x.png"))); // NOI18N
        paste.setText("Paste");
        paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteActionPerformed(evt);
            }
        });
        editar.add(paste);

        cut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/cut1x.png"))); // NOI18N
        cut.setText("Cut");
        editar.add(cut);
        editar.add(jSeparator1);

        delete_all.setBackground(new java.awt.Color(255, 0, 0));
        delete_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/delete_all1x.png"))); // NOI18N
        delete_all.setText("Delete All (TOO DANGEROUS)");
        delete_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_allActionPerformed(evt);
            }
        });
        editar.add(delete_all);
        delete_all.getAccessibleContext().setAccessibleDescription("");

        editar.add(jSeparator2);

        MainBar.add(editar);

        ayuda.setText("Help");
        ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ayudaMouseClicked(evt);
            }
        });

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/help1x.png"))); // NOI18N
        help.setText("Help & more");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        ayuda.add(help);
        ayuda.add(jSeparator3);

        acercade.setText("About...");
        acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercadeActionPerformed(evt);
            }
        });
        ayuda.add(acercade);

        githubr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icns/web1x.png"))); // NOI18N
        githubr.setText("Github repository");
        githubr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                githubrMouseClicked(evt);
            }
        });
        githubr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githubrActionPerformed(evt);
            }
        });
        ayuda.add(githubr);

        MainBar.add(ayuda);

        setJMenuBar(MainBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bienvenido)
                        .addGap(332, 332, 332))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(guardar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
        // TODO add your handling code here:
       this.textoeditar1.setText("");
    }//GEN-LAST:event_boton1MouseClicked

    private void ayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ayudaMouseClicked

    private void acercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acercadeActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void githubrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_githubrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_githubrMouseClicked

    private void githubrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githubrActionPerformed
        // TODO add your handling code here:
        try {
            
            String myurl = "https://github.com/carlop3333/datapack.creator/";
            
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(myurl));
            
        } catch (Exception e2) {
            //TODO handle exception
            e2.printStackTrace();
        }  
    }//GEN-LAST:event_githubrActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    private void delete_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_allActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_allActionPerformed

    private void copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyActionPerformed

    private void pasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasteActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
                try {
            
            String myurl = "https://github.com/carlop3333/datapack.creator/";
            
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(myurl));
            
        } catch (Exception e2) {
            //TODO handle exception
            e2.printStackTrace();
        }  
    }//GEN-LAST:event_helpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatapackCreatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatapackCreatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatapackCreatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatapackCreatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatapackCreatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MainBar;
    private javax.swing.JMenuItem acercade;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenu ayuda;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton boton1;
    private javax.swing.JMenuItem copy;
    private javax.swing.JMenuItem cut;
    private javax.swing.JMenuItem delete_all;
    private javax.swing.JMenu editar;
    private javax.swing.JMenuItem githubr;
    private javax.swing.JButton guardar;
    private javax.swing.JMenuItem help;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JMenuItem paste;
    private javax.swing.JMenuItem salir;
    private javax.swing.JTextArea textoeditar1;
    // End of variables declaration//GEN-END:variables


}
    



    


